### ISSUE TITLE
add youtube tutorial link

### ISSUE THREAD

**Issue by ymgan** [SIOS-Svalbard/Learnings_from_AeN_template_generator#50]
Hey @lhmarsden 

Thanks for sharing the tool with me, I think it's super well done and I am thinking to link it from our [hosted portal](https://antarctic.hp.gbif-staging.org/) (have not have time to update it) to promote its use. Will that be okay for you? Of course I will give SIOS and your team the credit so that people will not think that we are the ones who develop it.

I think it will be helpful to have the link to the [Youtube tutorial](https://youtu.be/DbvlwnYXuPU) somewhere in the template generator! Thanks a lot!!

**Comment by lhmarsden** [comment]
Wonderful, @ymgan. I will soon publish a snapshot of the repository to Zenodo and include a citation on the homepage somewhere, so people can credit me if they want when they use it. Let me know if you want any help adding it.

**Comment by lhmarsden** [comment]
There is a link to the YT tutorial in the latest commit. It hasn't been pulled to SIOS yet.

**Comment by lhmarsden** [comment]
@ymgan the latest commit also includes a recommended citation, now that v1.00 is published to Zenodo. Closing now.
